// Ambient shim: vendored `three` has no bundled types. Each export is exposed as both a
// type (`any`, usable in type positions) and a value (`any`, usable as a constructor).
declare module 'three' {
  export type WebGLRenderer = any;
  // The shader chunk table: a plain (unfrozen) object three resolves `#include <...>` from at compile
  // time. render.ts overrides `colorspace_fragment` in it — see postfx.ts for why (the offscreen
  // pixelation pass has to composite in display space, like the canvas).
  export const ShaderChunk: Record<string, string>;
export type ShaderMaterial = any;
export const ShaderMaterial: any;
export type WebGLRenderTarget = any;
export const WebGLRenderTarget: any;
  export const WebGLRenderer: any;
  export type Scene = any;
  export const Scene: any;
  export type PerspectiveCamera = any;
  export const PerspectiveCamera: any;
  export type OrthographicCamera = any;
  export const OrthographicCamera: any;
  export type Object3D = any;
  export const Object3D: any;
  export type Group = any;
  export const Group: any;
  export type Mesh = any;
  export const Mesh: any;
  export type InstancedMesh = any;
  export const InstancedMesh: any;
  export type SkinnedMesh = any;
  export const SkinnedMesh: any;
  export type Sprite = any;
  export const Sprite: any;
  export type Points = any;
  export const Points: any;
  export type Line = any;
  export const Line: any;
  export type LineSegments = any;
  export const LineSegments: any;
  export type MeshStandardMaterial = any;
  export const MeshStandardMaterial: any;
  export type MeshBasicMaterial = any;
  export const MeshBasicMaterial: any;
  export type MeshPhongMaterial = any;
  export const MeshPhongMaterial: any;
  export type MeshLambertMaterial = any;
  export const MeshLambertMaterial: any;
  export type MeshPhysicalMaterial = any;
  export const MeshPhysicalMaterial: any;
  export type MeshToonMaterial = any;
  export const MeshToonMaterial: any;
  export type SpriteMaterial = any;
  export const SpriteMaterial: any;
  export type PointsMaterial = any;
  export const PointsMaterial: any;
  export type LineBasicMaterial = any;
  export const LineBasicMaterial: any;
  export type HemisphereLight = any;
  export const HemisphereLight: any;
  export type AmbientLight = any;
  export const AmbientLight: any;
  export type DirectionalLight = any;
  export const DirectionalLight: any;
  export type PointLight = any;
  export const PointLight: any;
  export type SpotLight = any;
  export const SpotLight: any;
  export type PlaneGeometry = any;
  export const PlaneGeometry: any;
  export type BoxGeometry = any;
  export const BoxGeometry: any;
  export type SphereGeometry = any;
  export const SphereGeometry: any;
  export type CapsuleGeometry = any;
  export const CapsuleGeometry: any;
  export type ConeGeometry = any;
  export const ConeGeometry: any;
  export type CircleGeometry = any;
  export const CircleGeometry: any;
  export type CylinderGeometry = any;
  export const CylinderGeometry: any;
  export type RingGeometry = any;
  export const RingGeometry: any;
  export type Box3 = any;
  export const Box3: any;
  export type GridHelper = any;
  export const GridHelper: any;
  export type Color = any;
  export const Color: any;
  export type Vector2 = any;
  export const Vector2: any;
  export type Vector3 = any;
  export const Vector3: any;
  export type Quaternion = any;
  export const Quaternion: any;
  export type Matrix4 = any;
  export const Matrix4: any;
  export type Euler = any;
  export const Euler: any;
  export type Raycaster = any;
  export const Raycaster: any;
  export type BufferGeometry = any;
  export const BufferGeometry: any;
  export type BufferAttribute = any;
  export const BufferAttribute: any;
  export type Float32BufferAttribute = any;
  export const Float32BufferAttribute: any;
  export type AnimationMixer = any;
  export const AnimationMixer: any;
  export type AnimationClip = any;
  export const AnimationClip: any;
  export type Clock = any;
  export const Clock: any;
  export type CanvasTexture = any;
  export const CanvasTexture: any;
  export type Texture = any;
  export const Texture: any;
  export type DataTexture = any;
  export const DataTexture: any;
  export type TextureLoader = any;
  export const TextureLoader: any;
  export type CubeTextureLoader = any;
  export const CubeTextureLoader: any;
  export type LoadingManager = any;
  export const LoadingManager: any;
  export type MathUtils = any;
  export const MathUtils: any;
  export type DoubleSide = any;
  export const DoubleSide: any;
  export type FrontSide = any;
  export const FrontSide: any;
  export type BackSide = any;
  export const BackSide: any;
  export type AdditiveBlending = any;
  export const AdditiveBlending: any;
export const MultiplyBlending: any;
  export type RepeatWrapping = any;
  export const RepeatWrapping: any;
  export type SRGBColorSpace = any;
  export const SRGBColorSpace: any;
  export type NearestFilter = any;
  export const NearestFilter: any;
  export type RGBAFormat = any;
  export const RGBAFormat: any;
  export type UnsignedByteType = any;
  export const UnsignedByteType: any;
  export type PCFSoftShadowMap = any;
  export const PCFSoftShadowMap: any;
  export type DynamicDrawUsage = any;
  export const DynamicDrawUsage: any;
  export type StaticDrawUsage = any;
  export const StaticDrawUsage: any;
}
